[project]
name = "tt-precheck"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "gdstk",
    "klayout>=0.28.17.post1,<0.29.0",
    "numpy<2",
    "pytest",
    "PyYAML",
]

[tool.setuptools]
packages = []
