name: Precheck Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-precheck:
    runs-on: ubuntu-latest
    env:
      PDK_ROOT: /home/runner/pdk
      PDK_VERSION: d56f8a8ea0f9171cbdc5273035907b93f3f3bed7

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: precheck
        run: pip install -r requirements.txt

      - name: Install Sky130 PDK
        uses: TinyTapeout/ciel-action@v1
        with:
          pdk_name: sky130
          pdk_version: ${{ env.PDK_VERSION }}
          pdk_root: ${{ env.PDK_ROOT }}

      - name: Install Nix
        uses: rikhuijzer/cache-install@v1.1.4
        with:
          key: nix-${{ hashFiles('precheck/default.nix') }}
          nix_file: 'precheck/default.nix'

      - name: Build Nix packages
        working-directory: precheck
        run: nix-build

      - name: Run tests
        working-directory: precheck
        run: nix-shell --run "pytest --junit-xml=test_results.xml"
        
      - name: Test Summary
        uses: test-summary/action@v2.4
        with:
          paths: 'precheck/test_results.xml'
        if: always()
